version: 2

references:
  docker-config: &docker-config
    - image: docker.io/saltyrtc/circleci-image-js:firefox-66.0.5
      environment:
        FIREFOX_BIN: xvfb-firefox

jobs:
  test:
    docker: *docker-config
    steps:
      - checkout

      # Show version
      - run: node --version && npm --version

      # Install dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      # Run tests
      - run: npm run rollup_tests && npm test
      - run: node_modules/.bin/tsc --noEmit
  lint:
    docker: *docker-config
    steps:
      - checkout

      # Show version
      - run: node --version && npm --version

      # Install dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      # Run linter
      - run: npm run lint

workflows:
  version: 2
  build:
    jobs:
      - test
      - lint
